### PR TITLE
Updated to v0.88

### PR DESCRIPTION
**Pull request by peulaupeu**
- Added 1 Jamie scene to gallery

The new choice doesn't seem to matter

Also, I didn't update the gallery code, in case you want to. And I think the math.floor() function and the int() cast have exactly the same effect, so you could probably only keep one of the two (the way they are in the Hypnosis-Mod atm).

Cheers !

### CODE REVIEW

**Comment by peulaupeu** [comment]
Wait, don't pull that in, I forgot to check modifications of previous files ! I'll update this in a minute.

**Comment by peulaupeu** [comment]
OK, good to go, I believe !

**Comment by KiloOscarSix** [comment]
> Also, I didn't update the gallery code, in case you want to. And I think the math.floor() function and the int() cast have exactly the same effect, so you could probably only keep one of the two (the way they are in the Hypnosis-Mod atm).

Yeah, they are the same however `math.floor` is more obvious to me when I do eventually come back to this code.

**Comment by peulaupeu** [comment]
Yeah, since it didn't contain any scene nor choice, when checking for the changes applied by the mod on the original files I saw that it was the absolute same, except now upstream also contains a `jump ep22` at the end. Instead of adding that in the mod file, I thought we might as well not modify it at all :-) I guess back then I imported it before I realized I didn't need to touch it.
And about the `math.floor`, I absolutely agree ! I was just thiking you might as well do without the `int()` cast, since it is now useless.

**Comment by peulaupeu** [comment]
Since indeed the Jamie route looked blocked using the mod, I changer this choice, which does allow reaching Jamie scenes and doesn't seem to block any other content. So I'd say it's the right choice.

**Pull request merged**
